# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version.
VAGRANTFILE_API_VERSION = "2"

require 'yaml'

vm_config = YAML.load_file('config.yaml')

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	config.vm.box = "ubuntu/trusty64"
	
	config.vm.network "private_network", ip: vm_config["ip"]
	
	config.vm.provider "virtualbox" do |vb|
		vb.name 	= vm_config["name"]
		vb.gui 		= vm_config["gui"]
        vb.memory 	= vm_config["memory"]
        vb.cpus 	= vm_config["cpus"]
	end
end
